[build]
builder = "nixpacks"
buildCommand = "npm install && npm run build"

[variables]
NIXPACKS_NODE_VERSION = "24"

[deploy]
startCommand = "npm run start"
restartPolicyType = "on_failure"
restartPolicyMaxRetries = 3
